sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
script:
  - npm test
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t example .
  - docker tag example:latest 327426269989.dkr.ecr.us-east-1.amazonaws.com/example:latest
  - docker push 327426269989.dkr.ecr.us-east-1.amazonaws.com/example:latest